export const spanish_phrases = [
  "Liarlo parda",
  "Costar mogollón",
  "Estar al loro",
  "Pasarse tres pueblos",
  "Tener mala leche",
  "Que te den morcilla",
  "Se te ve el plumero",
  "Darse con un canto en los dientes",
  "Hablar por los codos",
  "Tener una empanada mental",
  "A freír espárragos",
  "Comerse el coco",
  "Estirar la pata",
  "Tener la mosca detrás de la oreja",
  "Planchar la oreja",
  "Dar calabazas a alguien",
  "Dar la vuelta a la tortilla",
  "Estar hasta las narices",
  "Tener la negra",
  "Hacerse un lío",
  "Llueve sobre mojado",
  "Echar una mano",
  "Tener mucho morro",
  "Estar flipando en colores",
  "Me lo estoy currando",
  "Comerse un marrón",
  "Comerse el tarro",
  "Dormir a pierna suelta",
  "Ser un melón",
  "Andar con pies de plomo",
  "Ponerse morado",
  "Estar sin blanca",
  "Estar como una cabra",
  "Tener vista de lince",
  "Dar plantón",
  "Otro gallo cantaría",
  "Muy cutre",
  "Liarse con alguien",
  "Ser sujetavelas",
  "Estar a dos velas",
  "Se le va la pinza",
  "No estar rayando",
  "Montar un pollo",
  "A tomar por saco",
  "Estar cotilleando",
  "Poner los cuernos",
  "Hincar los codos",
];
