export const spanish_proverbs = [
  "es más añejo que el vinagre",
  "es más bueno que el pan",
  "tiempo que se va, no vuelve más",
  "todo tiempo pasado, fue mejor",
  "lo quiero, para ayer",
  "siembra vientos y cosecha tempestades",
  "al país que fueres, haz lo que vieres",
  "quien te quiere te aporrea",
  "si se rasca, es porque le pica",
  "quedó para vestir santos",
  "quedo mirando para el norte",
  "desvestir un santo para vestir otro",
  "que le hace el agua al pescado",
  "que más le hace una raya al tigre",
  "de lo bueno, poco",
  "por la boca muere el pez",
  "preguntando, se llega a roma",
  "para muestra, un boton",
  "la excepcion confirma la regla",
  "el leon no es tan bravo como lo pintan",
  "no hagas leña del arbol caido",
  "roma no se hizo en un día",
  "no me picotee las uvas",
  "algo es algo, peor es nada",
  "a otro perro con ese hueso",
  "como traje a la medida",
  "amor con amor se paga",
  "el que la hace la paga",
  "de tal palo, tal astilla",
  "juntos, pero no revueltos",
];
