export const spanish_proverbs = [
  "El elefante es un animal muy grande",
  "Mi nombre es Robot y me gusta ayudar",
  "a otro perro con ese hueso",
  "al pais que fueres, haz lo que vieres",
  "algo es algo, peor es nada",
  "amor con amor se paga",
  "como traje a la medida",
  "de lo bueno, poco",
  "de tal palo, tal astilla",
  "desvestir un santo para vestir otro",
  "el leon no es tan bravo como lo pintan",
  "el que la hace la paga",
  "es mas añejo que el vinagre",
  "es mas bueno que el pan",
  "juntos, pero no revueltos",
  "la excepcion confirma la regla",
  "lo quiero, para ayer",
  "no hagas leña del arbol caido",
  "no me picotee las uvas",
  "para muestra, un boton",
  "por la boca muere el pez",
  "preguntando, se llega a roma",
  "quedo para vestir santos",
  "quedo mirando para el norte",
  "que le hace el agua al pescado",
  "que mas le hace una raya al tigre",
  "quien te quiere te aporrea",
  "roma no se hizo en un dia",
  "si se rasca, es porque le pica",
  "siembra vientos y cosecha tempestades",
  "tiempo que se va, no vuelve mas",
  "todo tiempo pasado, fue mejor",
];
